// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=./mocks/mock_booking.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	model "github.com/internships-backend/test-backend-barashF/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockbookingRepository is a mock of bookingRepository interface.
type MockbookingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockbookingRepositoryMockRecorder
	isgomock struct{}
}

// MockbookingRepositoryMockRecorder is the mock recorder for MockbookingRepository.
type MockbookingRepositoryMockRecorder struct {
	mock *MockbookingRepository
}

// NewMockbookingRepository creates a new mock instance.
func NewMockbookingRepository(ctrl *gomock.Controller) *MockbookingRepository {
	mock := &MockbookingRepository{ctrl: ctrl}
	mock.recorder = &MockbookingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbookingRepository) EXPECT() *MockbookingRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockbookingRepository) Create(arg0 context.Context, arg1 *model.Booking) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockbookingRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockbookingRepository)(nil).Create), arg0, arg1)
}

// GetAllWithPagination mocks base method.
func (m *MockbookingRepository) GetAllWithPagination(ctx context.Context, pageSize, offset int) ([]*model.Booking, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWithPagination", ctx, pageSize, offset)
	ret0, _ := ret[0].([]*model.Booking)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllWithPagination indicates an expected call of GetAllWithPagination.
func (mr *MockbookingRepositoryMockRecorder) GetAllWithPagination(ctx, pageSize, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWithPagination", reflect.TypeOf((*MockbookingRepository)(nil).GetAllWithPagination), ctx, pageSize, offset)
}

// GetByID mocks base method.
func (m *MockbookingRepository) GetByID(arg0 context.Context, arg1 uuid.UUID) (*model.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*model.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockbookingRepositoryMockRecorder) GetByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockbookingRepository)(nil).GetByID), arg0, arg1)
}

// GetByUserID mocks base method.
func (m *MockbookingRepository) GetByUserID(arg0 context.Context, arg1 uuid.UUID) ([]*model.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", arg0, arg1)
	ret0, _ := ret[0].([]*model.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockbookingRepositoryMockRecorder) GetByUserID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockbookingRepository)(nil).GetByUserID), arg0, arg1)
}

// UpdateStatus mocks base method.
func (m *MockbookingRepository) UpdateStatus(arg0 context.Context, arg1 uuid.UUID, arg2 model.BookingStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockbookingRepositoryMockRecorder) UpdateStatus(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockbookingRepository)(nil).UpdateStatus), arg0, arg1, arg2)
}

// MockslotRepository is a mock of slotRepository interface.
type MockslotRepository struct {
	ctrl     *gomock.Controller
	recorder *MockslotRepositoryMockRecorder
	isgomock struct{}
}

// MockslotRepositoryMockRecorder is the mock recorder for MockslotRepository.
type MockslotRepositoryMockRecorder struct {
	mock *MockslotRepository
}

// NewMockslotRepository creates a new mock instance.
func NewMockslotRepository(ctrl *gomock.Controller) *MockslotRepository {
	mock := &MockslotRepository{ctrl: ctrl}
	mock.recorder = &MockslotRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockslotRepository) EXPECT() *MockslotRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockslotRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.Slot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockslotRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockslotRepository)(nil).GetByID), ctx, id)
}

// UpdateIsBooked mocks base method.
func (m *MockslotRepository) UpdateIsBooked(ctx context.Context, id uuid.UUID, isBooked bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIsBooked", ctx, id, isBooked)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIsBooked indicates an expected call of UpdateIsBooked.
func (mr *MockslotRepositoryMockRecorder) UpdateIsBooked(ctx, id, isBooked any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIsBooked", reflect.TypeOf((*MockslotRepository)(nil).UpdateIsBooked), ctx, id, isBooked)
}

// MockconferenceGateway is a mock of conferenceGateway interface.
type MockconferenceGateway struct {
	ctrl     *gomock.Controller
	recorder *MockconferenceGatewayMockRecorder
	isgomock struct{}
}

// MockconferenceGatewayMockRecorder is the mock recorder for MockconferenceGateway.
type MockconferenceGatewayMockRecorder struct {
	mock *MockconferenceGateway
}

// NewMockconferenceGateway creates a new mock instance.
func NewMockconferenceGateway(ctrl *gomock.Controller) *MockconferenceGateway {
	mock := &MockconferenceGateway{ctrl: ctrl}
	mock.recorder = &MockconferenceGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconferenceGateway) EXPECT() *MockconferenceGatewayMockRecorder {
	return m.recorder
}

// CreateConference mocks base method.
func (m *MockconferenceGateway) CreateConference(arg0 context.Context, arg1 uuid.UUID, arg2 time.Time) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConference", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateConference indicates an expected call of CreateConference.
func (mr *MockconferenceGatewayMockRecorder) CreateConference(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConference", reflect.TypeOf((*MockconferenceGateway)(nil).CreateConference), arg0, arg1, arg2)
}

// Mockmanager is a mock of manager interface.
type Mockmanager struct {
	ctrl     *gomock.Controller
	recorder *MockmanagerMockRecorder
	isgomock struct{}
}

// MockmanagerMockRecorder is the mock recorder for Mockmanager.
type MockmanagerMockRecorder struct {
	mock *Mockmanager
}

// NewMockmanager creates a new mock instance.
func NewMockmanager(ctrl *gomock.Controller) *Mockmanager {
	mock := &Mockmanager{ctrl: ctrl}
	mock.recorder = &MockmanagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockmanager) EXPECT() *MockmanagerMockRecorder {
	return m.recorder
}

// InTransaction mocks base method.
func (m *Mockmanager) InTransaction(ctx context.Context, options *model.TransactionOptions, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InTransaction", ctx, options, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// InTransaction indicates an expected call of InTransaction.
func (mr *MockmanagerMockRecorder) InTransaction(ctx, options, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InTransaction", reflect.TypeOf((*Mockmanager)(nil).InTransaction), ctx, options, fn)
}
