services:
    service-booking:
        build: .
        container_name: service-booking
        ports:
            - "8080:8080"
            - "6060:6060"
        environment:
            - PORT=8080

            - POSTGRES_HOST=booking-database
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=booking_db

            - JWT_SECRET=super_secret_default_key_123
            - JWT_TTL=24h
        depends_on:
            booking-database:
                condition: service_healthy
        networks:
            - booking

    booking-database:
        image: postgres:15
        container_name: booking-database
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=booking_db
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d booking_db"]
            interval: 5s
            timeout: 5s
            retries: 5
        command:
            ["postgres", "-c", "shared_preload_libraries=pg_stat_statements"]
        networks:
            - booking

    prometheus:
        image: prom/prometheus
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - "9090:9090"
        networks:
            - booking

    grafana:
        image: grafana/grafana
        volumes:
            - ./grafana/provisioning:/etc/grafana/provisioning
            - ./grafana/dashboards:/etc/grafana/dashboards
        ports:
            - "3000:3000"
        networks:
            - booking

    redis:
        image: redis:7.2-alpine
        container_name: crm_redis
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        command: redis-server --appendonly yes --appendfsync everysec
        networks:
            - booking

    redis-insight:
        image: redis/redisinsight:latest
        container_name: crm_redis_insight
        restart: always
        ports:
            - "5540:5540"
        volumes:
            - redis_insight_data:/db
        depends_on:
            - redis
        networks:
            - booking

networks:
    booking:

volumes:
    pgdata:
    redis_data:
    redis_insight_data:
