// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=./mocks/mock_schedule.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	"github.com/internships-backend/test-backend-barashF/internal/logger"
	model "github.com/internships-backend/test-backend-barashF/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockscheduleRepository is a mock of scheduleRepository interface.
type MockscheduleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockscheduleRepositoryMockRecorder
	isgomock struct{}
}

// MockscheduleRepositoryMockRecorder is the mock recorder for MockscheduleRepository.
type MockscheduleRepositoryMockRecorder struct {
	mock *MockscheduleRepository
}

// NewMockscheduleRepository creates a new mock instance.
func NewMockscheduleRepository(ctrl *gomock.Controller) *MockscheduleRepository {
	mock := &MockscheduleRepository{ctrl: ctrl}
	mock.recorder = &MockscheduleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockscheduleRepository) EXPECT() *MockscheduleRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockscheduleRepository) Create(arg0 context.Context, arg1 *model.Schedule) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockscheduleRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockscheduleRepository)(nil).Create), arg0, arg1)
}

// GetByRoomID mocks base method.
func (m *MockscheduleRepository) GetByRoomID(ctx context.Context, roomID uuid.UUID) (*model.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRoomID", ctx, roomID)
	ret0, _ := ret[0].(*model.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRoomID indicates an expected call of GetByRoomID.
func (mr *MockscheduleRepositoryMockRecorder) GetByRoomID(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRoomID", reflect.TypeOf((*MockscheduleRepository)(nil).GetByRoomID), ctx, roomID)
}

// MockroomRepository is a mock of roomRepository interface.
type MockroomRepository struct {
	ctrl     *gomock.Controller
	recorder *MockroomRepositoryMockRecorder
	isgomock struct{}
}

// MockroomRepositoryMockRecorder is the mock recorder for MockroomRepository.
type MockroomRepositoryMockRecorder struct {
	mock *MockroomRepository
}

// NewMockroomRepository creates a new mock instance.
func NewMockroomRepository(ctrl *gomock.Controller) *MockroomRepository {
	mock := &MockroomRepository{ctrl: ctrl}
	mock.recorder = &MockroomRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockroomRepository) EXPECT() *MockroomRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockroomRepository) GetByID(arg0 context.Context, arg1 uuid.UUID) (*model.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*model.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockroomRepositoryMockRecorder) GetByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockroomRepository)(nil).GetByID), arg0, arg1)
}

// MockslotRepository is a mock of slotRepository interface.
type MockslotRepository struct {
	ctrl     *gomock.Controller
	recorder *MockslotRepositoryMockRecorder
	isgomock struct{}
}

// MockslotRepositoryMockRecorder is the mock recorder for MockslotRepository.
type MockslotRepositoryMockRecorder struct {
	mock *MockslotRepository
}

// NewMockslotRepository creates a new mock instance.
func NewMockslotRepository(ctrl *gomock.Controller) *MockslotRepository {
	mock := &MockslotRepository{ctrl: ctrl}
	mock.recorder = &MockslotRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockslotRepository) EXPECT() *MockslotRepositoryMockRecorder {
	return m.recorder
}

// CreateMany mocks base method.
func (m *MockslotRepository) CreateMany(arg0 context.Context, arg1 []*model.Slot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMany", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMany indicates an expected call of CreateMany.
func (mr *MockslotRepositoryMockRecorder) CreateMany(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMany", reflect.TypeOf((*MockslotRepository)(nil).CreateMany), arg0, arg1)
}

// Mockmanager is a mock of manager interface.
type Mockmanager struct {
	ctrl     *gomock.Controller
	recorder *MockmanagerMockRecorder
	isgomock struct{}
}

// MockmanagerMockRecorder is the mock recorder for Mockmanager.
type MockmanagerMockRecorder struct {
	mock *Mockmanager
}

// NewMockmanager creates a new mock instance.
func NewMockmanager(ctrl *gomock.Controller) *Mockmanager {
	mock := &Mockmanager{ctrl: ctrl}
	mock.recorder = &MockmanagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockmanager) EXPECT() *MockmanagerMockRecorder {
	return m.recorder
}

// InTransaction mocks base method.
func (m *Mockmanager) InTransaction(ctx context.Context, options *model.TransactionOptions, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InTransaction", ctx, options, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// InTransaction indicates an expected call of InTransaction.
func (mr *MockmanagerMockRecorder) InTransaction(ctx, options, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InTransaction", reflect.TypeOf((*Mockmanager)(nil).InTransaction), ctx, options, fn)
}

type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockLogger) Debug(msg string, fields ...logger.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debug", varargs...)
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerMockRecorder) Debug(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLogger)(nil).Debug), varargs...)
}

// Error mocks base method.
func (m *MockLogger) Error(msg string, fields ...logger.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), varargs...)
}

// Info mocks base method.
func (m *MockLogger) Info(msg string, fields ...logger.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), varargs...)
}

// Sync mocks base method.
func (m *MockLogger) Sync() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync")
	ret0, _ := ret[0].(error)
	return ret0
}

// Sync indicates an expected call of Sync.
func (mr *MockLoggerMockRecorder) Sync() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockLogger)(nil).Sync))
}

// Warn mocks base method.
func (m *MockLogger) Warn(msg string, fields ...logger.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warn", varargs...)
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerMockRecorder) Warn(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLogger)(nil).Warn), varargs...)
}
