// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=./mocks/mock_slot.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	model "github.com/internships-backend/test-backend-barashF/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockslotService is a mock of slotService interface.
type MockslotService struct {
	ctrl     *gomock.Controller
	recorder *MockslotServiceMockRecorder
	isgomock struct{}
}

// MockslotServiceMockRecorder is the mock recorder for MockslotService.
type MockslotServiceMockRecorder struct {
	mock *MockslotService
}

// NewMockslotService creates a new mock instance.
func NewMockslotService(ctrl *gomock.Controller) *MockslotService {
	mock := &MockslotService{ctrl: ctrl}
	mock.recorder = &MockslotServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockslotService) EXPECT() *MockslotServiceMockRecorder {
	return m.recorder
}

// GetAvailableSlotsByDate mocks base method.
func (m *MockslotService) GetAvailableSlotsByDate(arg0 context.Context, arg1 uuid.UUID, arg2 time.Time) ([]*model.Slot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableSlotsByDate", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*model.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableSlotsByDate indicates an expected call of GetAvailableSlotsByDate.
func (mr *MockslotServiceMockRecorder) GetAvailableSlotsByDate(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableSlotsByDate", reflect.TypeOf((*MockslotService)(nil).GetAvailableSlotsByDate), arg0, arg1, arg2)
}
