// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=./mocks/mock_schedule.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/internships-backend/test-backend-barashF/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockscheduleService is a mock of scheduleService interface.
type MockscheduleService struct {
	ctrl     *gomock.Controller
	recorder *MockscheduleServiceMockRecorder
	isgomock struct{}
}

// MockscheduleServiceMockRecorder is the mock recorder for MockscheduleService.
type MockscheduleServiceMockRecorder struct {
	mock *MockscheduleService
}

// NewMockscheduleService creates a new mock instance.
func NewMockscheduleService(ctrl *gomock.Controller) *MockscheduleService {
	mock := &MockscheduleService{ctrl: ctrl}
	mock.recorder = &MockscheduleServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockscheduleService) EXPECT() *MockscheduleServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockscheduleService) Create(ctx context.Context, roomID uuid.UUID, daysOfWeek model.DaysOfWeek, startTimeStr, endTimeStr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, roomID, daysOfWeek, startTimeStr, endTimeStr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockscheduleServiceMockRecorder) Create(ctx, roomID, daysOfWeek, startTimeStr, endTimeStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockscheduleService)(nil).Create), ctx, roomID, daysOfWeek, startTimeStr, endTimeStr)
}
