// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=./mocks/mock_room.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/internships-backend/test-backend-barashF/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockroomService is a mock of roomService interface.
type MockroomService struct {
	ctrl     *gomock.Controller
	recorder *MockroomServiceMockRecorder
	isgomock struct{}
}

// MockroomServiceMockRecorder is the mock recorder for MockroomService.
type MockroomServiceMockRecorder struct {
	mock *MockroomService
}

// NewMockroomService creates a new mock instance.
func NewMockroomService(ctrl *gomock.Controller) *MockroomService {
	mock := &MockroomService{ctrl: ctrl}
	mock.recorder = &MockroomServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockroomService) EXPECT() *MockroomServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockroomService) Create(arg0 context.Context, arg1 *model.Room) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockroomServiceMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockroomService)(nil).Create), arg0, arg1)
}

// List mocks base method.
func (m *MockroomService) List(arg0 context.Context) ([]*model.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]*model.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockroomServiceMockRecorder) List(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockroomService)(nil).List), arg0)
}
