// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=./mocks/mock_slot.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	model "github.com/internships-backend/test-backend-barashF/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockslotRepository is a mock of slotRepository interface.
type MockslotRepository struct {
	ctrl     *gomock.Controller
	recorder *MockslotRepositoryMockRecorder
	isgomock struct{}
}

// MockslotRepositoryMockRecorder is the mock recorder for MockslotRepository.
type MockslotRepositoryMockRecorder struct {
	mock *MockslotRepository
}

// NewMockslotRepository creates a new mock instance.
func NewMockslotRepository(ctrl *gomock.Controller) *MockslotRepository {
	mock := &MockslotRepository{ctrl: ctrl}
	mock.recorder = &MockslotRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockslotRepository) EXPECT() *MockslotRepositoryMockRecorder {
	return m.recorder
}

// GetByRoomAndDate mocks base method.
func (m *MockslotRepository) GetByRoomAndDate(arg0 context.Context, arg1 uuid.UUID, arg2 time.Time) ([]*model.Slot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRoomAndDate", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*model.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRoomAndDate indicates an expected call of GetByRoomAndDate.
func (mr *MockslotRepositoryMockRecorder) GetByRoomAndDate(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRoomAndDate", reflect.TypeOf((*MockslotRepository)(nil).GetByRoomAndDate), arg0, arg1, arg2)
}

// MockroomRepository is a mock of roomRepository interface.
type MockroomRepository struct {
	ctrl     *gomock.Controller
	recorder *MockroomRepositoryMockRecorder
	isgomock struct{}
}

// MockroomRepositoryMockRecorder is the mock recorder for MockroomRepository.
type MockroomRepositoryMockRecorder struct {
	mock *MockroomRepository
}

// NewMockroomRepository creates a new mock instance.
func NewMockroomRepository(ctrl *gomock.Controller) *MockroomRepository {
	mock := &MockroomRepository{ctrl: ctrl}
	mock.recorder = &MockroomRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockroomRepository) EXPECT() *MockroomRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockroomRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockroomRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockroomRepository)(nil).GetByID), ctx, id)
}
