// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=./mocks/mock_booking.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/internships-backend/test-backend-barashF/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockbookingService is a mock of bookingService interface.
type MockbookingService struct {
	ctrl     *gomock.Controller
	recorder *MockbookingServiceMockRecorder
	isgomock struct{}
}

// MockbookingServiceMockRecorder is the mock recorder for MockbookingService.
type MockbookingServiceMockRecorder struct {
	mock *MockbookingService
}

// NewMockbookingService creates a new mock instance.
func NewMockbookingService(ctrl *gomock.Controller) *MockbookingService {
	mock := &MockbookingService{ctrl: ctrl}
	mock.recorder = &MockbookingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbookingService) EXPECT() *MockbookingServiceMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockbookingService) Cancel(ctx context.Context, bookingID, userID uuid.UUID) (*model.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, bookingID, userID)
	ret0, _ := ret[0].(*model.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cancel indicates an expected call of Cancel.
func (mr *MockbookingServiceMockRecorder) Cancel(ctx, bookingID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockbookingService)(nil).Cancel), ctx, bookingID, userID)
}

// Create mocks base method.
func (m *MockbookingService) Create(ctx context.Context, userID, slotID uuid.UUID, createConferenceLink bool) (*model.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, slotID, createConferenceLink)
	ret0, _ := ret[0].(*model.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockbookingServiceMockRecorder) Create(ctx, userID, slotID, createConferenceLink any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockbookingService)(nil).Create), ctx, userID, slotID, createConferenceLink)
}

// GetByUser mocks base method.
func (m *MockbookingService) GetByUser(arg0 context.Context, arg1 uuid.UUID) ([]*model.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUser", arg0, arg1)
	ret0, _ := ret[0].([]*model.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUser indicates an expected call of GetByUser.
func (mr *MockbookingServiceMockRecorder) GetByUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUser", reflect.TypeOf((*MockbookingService)(nil).GetByUser), arg0, arg1)
}

// List mocks base method.
func (m *MockbookingService) List(ctx context.Context, page, pageSize int) ([]*model.Booking, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, pageSize)
	ret0, _ := ret[0].([]*model.Booking)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockbookingServiceMockRecorder) List(ctx, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockbookingService)(nil).List), ctx, page, pageSize)
}
