// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bookings/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bookings"
                ],
                "summary": "Создать бронь на слот (только user).",
                "parameters": [
                    {
                        "description": "Данные для создания бронирования",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Бронь создана",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.BookingCreateResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещён (бронирование доступно только роли user)",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Слот не найден",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Слот уже занят",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/bookings/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Доступно только роли admin. Поддерживает пагинацию.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bookings"
                ],
                "summary": "Список всех броней с пагинацией (только admin)",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Номер страницы (начиная с 1). По умолчанию 1.",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Количество записей на странице. По умолчанию 20, максимум 100.",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список всех броней и метаданные пагинации",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.BookingListPaginatationResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос (некорректные параметры пагинации)",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещён (только admin)",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/bookings/my": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Доступно только роли user. Возвращает брони пользователя.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bookings"
                ],
                "summary": "Список броней текущего пользователя (только user)",
                "responses": {
                    "200": {
                        "description": "Список броней текущего пользователя",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.BookingListResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещён (только user)",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/bookings/{bookingId}/cancel": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Доступно только роли user. Пользователь может отменить только свою бронь.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bookings"
                ],
                "summary": "Отменить бронь (только своя бронь, только user)",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Идентификатор брони (UUID)",
                        "name": "bookingId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Бронь отменена (или уже была отменена ранее)",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.BookingCreateResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат ID брони",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Не своя бронь или роль не user",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Бронь не найдена",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dummyLogin": {
            "post": {
                "description": "Выдаёт тестовый JWT для указанной роли (admin / user).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Получить тестовый JWT по роли. Доступен без авторизации.",
                "parameters": [
                    {
                        "description": "Запрос на получение тестового токена",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_auth.DummyLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Тестовый токен",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_auth.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос (недопустимое значение роли)",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_auth.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Авторизует пользователя по email и паролю, возвращает JWT.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Авторизация по email и паролю",
                "parameters": [
                    {
                        "description": "Учетные данные пользователя",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная авторизация (возвращает токен)",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_auth.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_auth.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Неверные учётные данные",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_auth.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Создаёт нового пользователя и возвращает его id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Регистрация пользователя",
                "parameters": [
                    {
                        "description": "Данные для регистрации пользователя",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Пользователь создан",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_auth.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос или email уже занят",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_auth.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/rooms/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создает новую переговорную комнату.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rooms"
                ],
                "summary": "Создать переговорку (только admin)",
                "parameters": [
                    {
                        "description": "Данные для создания комнаты",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_room.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Переговорка создана",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_room.RoomCreateResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_room.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_room.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещён (требуется роль admin)",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_room.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_room.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/rooms/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает список всех доступных переговорных комнат.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rooms"
                ],
                "summary": "Список переговорок (admin и user)",
                "responses": {
                    "200": {
                        "description": "Список переговорок",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_room.RoomListResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_room.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_room.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/rooms/{roomId}/schedule/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Schedules"
                ],
                "summary": "Создать расписание переговорки (только admin, только один раз). Длительность слота 30 мин.",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Идентификатор переговорки (UUID)",
                        "name": "roomId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для создания расписания",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_schedule.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Расписание сохранено",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_schedule.CreateResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос (в т.ч. недопустимые значения daysOfWeek)",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_schedule.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_schedule.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещён (требуется роль admin)",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_schedule.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Переговорка не найдена",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_schedule.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Расписание для переговорки уже создано, изменение не допускается",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_schedule.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_schedule.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/rooms/{roomId}/slots/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает слоты, не занятые активной бронью, для указанной переговорки на указанную дату. Все даты и время передаются и возвращаются в UTC. Параметр date является обязательным; при его отсутствии возвращается 400. Если у переговорки нет расписания — возвращается пустой список (переговорка считается всегда недоступной).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Slots"
                ],
                "summary": "Список доступных для бронирования слотов по переговорке и дате (admin и user). Наиболее нагруженный эндпоинт.",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Идентификатор переговорки (UUID)",
                        "name": "roomId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "date",
                        "description": "Дата в формате ISO 8601 (например: 2024-06-10). Обязательный параметр.",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список доступных слотов",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_slot.SlotListResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос (отсутствует или некорректен параметр date)",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_slot.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_slot.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Переговорка не найдена",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_slot.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_slot.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_internships-backend_test-backend-barashF_internal_handler_dto_auth.AuthResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                }
            }
        },
        "github_com_internships-backend_test-backend-barashF_internal_handler_dto_auth.DummyLoginRequest": {
            "type": "object",
            "properties": {
                "role": {
                    "type": "string"
                }
            }
        },
        "github_com_internships-backend_test-backend-barashF_internal_handler_dto_auth.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "текст ошибки или причина отказа"
                }
            }
        },
        "github_com_internships-backend_test-backend-barashF_internal_handler_dto_auth.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "github_com_internships-backend_test-backend-barashF_internal_handler_dto_auth.RegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "github_com_internships-backend_test-backend-barashF_internal_handler_dto_auth.RegisterResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.BookingCreateResponse": {
            "type": "object",
            "properties": {
                "booking": {
                    "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.Response"
                }
            }
        },
        "github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.BookingListPaginatationResponse": {
            "type": "object",
            "properties": {
                "bookings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.Response"
                    }
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.BookingListResponse": {
            "type": "object",
            "properties": {
                "bookings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.Response"
                    }
                }
            }
        },
        "github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.CreateRequest": {
            "type": "object",
            "properties": {
                "create_conference_link": {
                    "type": "boolean"
                },
                "slot_id": {
                    "type": "string"
                }
            }
        },
        "github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "текст ошибки или причина отказа"
                }
            }
        },
        "github_com_internships-backend_test-backend-barashF_internal_handler_dto_booking.Response": {
            "type": "object",
            "properties": {
                "conference_link": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "slot_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_internships-backend_test-backend-barashF_internal_handler_dto_room.CreateRequest": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_internships-backend_test-backend-barashF_internal_handler_dto_room.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "текст ошибки или причина отказа"
                }
            }
        },
        "github_com_internships-backend_test-backend-barashF_internal_handler_dto_room.RoomCreateResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "github_com_internships-backend_test-backend-barashF_internal_handler_dto_room.RoomListResponse": {
            "type": "object",
            "properties": {
                "rooms": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_room.RoomResponse"
                    }
                }
            }
        },
        "github_com_internships-backend_test-backend-barashF_internal_handler_dto_room.RoomResponse": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_internships-backend_test-backend-barashF_internal_handler_dto_schedule.CreateRequest": {
            "type": "object",
            "properties": {
                "days_of_week": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "end_time": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "github_com_internships-backend_test-backend-barashF_internal_handler_dto_schedule.CreateResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_internships-backend_test-backend-barashF_internal_handler_dto_schedule.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "текст ошибки или причина отказа"
                }
            }
        },
        "github_com_internships-backend_test-backend-barashF_internal_handler_dto_slot.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "текст ошибки или причина отказа"
                }
            }
        },
        "github_com_internships-backend_test-backend-barashF_internal_handler_dto_slot.SlotListResponse": {
            "type": "object",
            "properties": {
                "slots": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_internships-backend_test-backend-barashF_internal_handler_dto_slot.SlotResponse"
                    }
                }
            }
        },
        "github_com_internships-backend_test-backend-barashF_internal_handler_dto_slot.SlotResponse": {
            "type": "object",
            "properties": {
                "end": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_booked": {
                    "type": "boolean"
                },
                "room_id": {
                    "type": "string"
                },
                "start": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Room Booking Service",
	Description:      "Сервис бронирования переговорок",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
