name: CI Pipeline

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main]

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Build app
              run: echo "Собираем приложение..."

    security-check:
        permissions:
            security-events: write
            contents: read
        uses: barashF/security-templates/.github/workflows/scanner.yml@main
