name: DevSecOps Advanced Scan

on:
    push:
        branches: ["main", "master"]
    pull_request:
        branches: ["main", "master"]

jobs:
    trivy-scan:
        name: Run Trivy with Reports
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            # Шаг 1: Сканируем ВСЁ, формируем отчет в формате SARIF (стандарт для GitHub), но НЕ роняем пайплайн
            - name: Generate Security Report
              uses: aquasecurity/trivy-action@master
              with:
                  scan-type: "fs"
                  scan-ref: "."
                  scanners: "vuln,secret"
                  format: "sarif"
                  output: "trivy-results.sarif"

            # Шаг 2: Загружаем этот отчет в интерфейс самого GitHub
            - name: Upload Trivy scan results to GitHub Security tab
              uses: github/codeql-action/upload-sarif@v3
              with:
                  sarif_file: "trivy-results.sarif"

            # Шаг 3: А вот теперь делаем жесткую проверку. Если есть HIGH или CRITICAL — вот тут роняем сборку
            - name: Block on High/Critical
              uses: aquasecurity/security-action@master # упрощенный вызов для проверки условий
              with:
                  scan-type: "fs"
                  severity: "HIGH,CRITICAL"
                  exit-code: "1"
